apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-todo-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-todo
  template:
    metadata:
      labels:
        app: node-todo
    spec:
      containers:
        - name: node-todo-container
          image: __IMAGE_TAG__   # ✅ Placeholder to be replaced by Jenkins
          ports:
            - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: node-todo-service
spec:
  type: LoadBalancer   # ✅ Exposes publicly on supported cloud
  selector:
    app: node-todo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000

