apiVersion: apps/v1
kind: Deployment
metadata:
  name: note-todo-deployment
spec:
  replicas: 3  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: note-todo
  template:
    metadata:
      labels:
        app: note-todo
    spec:
      containers:
        - name: note-todo-container
          image: ripon836/note-todo:latest  # Use your actual Docker image name and tag
          ports:
            - containerPort: 8000  # The port your React app is listening on

---
apiVersion: v1
kind: Service
metadata:
  name: note-todo-service
spec:
  selector:
    app: note-todo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30080
  type: NodePort
